# build stage
FROM node:14.18.1 as build

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn install --production --frozen-lockfile

COPY . .

RUN yarn add --dev typescript @types/react @types/node

RUN yarn build

# production stage
FROM nginx:1.18.0 as prod

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/.next /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
