FROM node:14.18.1 as dev

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn

ENV REACT_APP_MAP_WEB_API_KEY=$REACT_APP_MAP_WEB_API_KEY
ENV REACT_APP_NAME=$REACT_APP_NAME

COPY . .

CMD [ "yarn", "start" ]
