const delegationTypes = [
    { value: "فروش" },
    { value: "معاوضه" },
    { value: "رهن" },
    { value: "اجاره" },
    { value: "پیش‌فروش" },
    { value: "مشارکت در ساخت" },
    { value: "مشارکت در بهره برداری" },
];

const estateTypes = [
    { value: "خانه" },
    { value: "آپارتمان" },
    { value: "ویلا" },
    { value: "زمین مسکونی" },
    { value: "زمین کشاورزی" },
    { value: "باغ" },
    { value: "مغازه" },
    { value: "دفتر کار" },
    { value: "زیرزمین" },
    { value: "انبار" },
    { value: "پارکینگ" },
    { value: "گاراژ" },
    { value: "کارگاه" },
    { value: "کارخانه" },
    { value: "مرغداری" },
    { value: "دامداری" },
    { value: "سردخانه" },
    { value: "هتل" },
    { value: "مسافرخانه" },
    { value: "رستوران" },
    { value: "سوئیت" },
    { value: "تالار عروسی" },
    { value: "معدن" },
    { value: "وام" },
    { value: "فیش" },
    { value: "جایگاه سوخت" },
    { value: "سوله" },
];

export { delegationTypes, estateTypes };
