class Strings {
  static unknownError = 'خطای ناشناخته در سیستم';
  static delegationTypes = 'نوع واگذاری‌ها';
  static estateTypes = 'نوع ملک‌ها';
  static provinces = 'استان‌ها';
  static cities = 'شهر‌ها';
  static units = 'واحدها';
  static forms = 'فرم‌ها';
  static owners = 'مالک‌ها';
  static admins = 'ادمین‌ها';
  static users = 'کاربرها';
  static addNewType = 'افزودن نوع جدید';
  static saveChanges = 'ذخیره تغییرات';
  static saveChangesSuccess = 'تغییرات با موفقیت ذخیره شد';
  static saveChangesError = 'خطا در ذخیره سازی تغییرات';
  static choose = 'انتخاب کنید';
  static addNewCity = 'افزودن شهر جدید';
  static addNewUnit = 'افزودن واحد جدید';
  static login = 'ورود';
  static sajaLogin = 'ورود به سامانه ثجا';
  static sajaSignup = 'ثبت نام در سامانه ثجا';
  static mobile = 'شماره موبایل';
  static password = 'گذرواژه';
  static repeatPassword = 'تکرار گذرواژه';
  static showPassword = 'نمایش گذرواژه';
  static forgotPassowrd = 'آیا گذرواژه خود را فراموش کرده‌اید؟';
  static recoverPassword = 'بازیابی گذرواژه';
  static dontHaveAnAccount = 'حساب کاربری ندارید؟';
  static doHaveAnAccount = 'حساب کاربری دارید؟';
  static signup = 'ثبت نام';
  static invalidPhoneNumber = 'شماره موبایل واردشده نامعتبر است';
  static invalidPassword = 'گذرواژه باید بین ۸ تا ۱۶ کاراکتر باشد';
  static invalidRepeatPassword = 'گذرواژه‌های واردشده یکسان نیستند';
  static editProfile = 'ویرایش حساب کاربری';
  static changePassword = 'تغییر گذرواژه';
  static logout = 'خروج از حساب کاربری';
  static fullName = 'نام و نام خانوادگی';
  static cancel = 'لغو';
  static save = 'ذخیره';
  static newPassword = 'گذرواژه جدید';
  static currentPassword = 'گذرواژه کنونی';
  static repeatNewPassword = 'تکرار گذرواژه جدید';
}

export default Strings;
