name: deploy-website

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }} 
    steps:
      - uses: actions/checkout@v2
      - run: make build-remote
      - run: make password=$DOCKER_PASSWORD login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: make push-remote
      - run: make logout
      - uses: appleboy/ssh-action@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          envs: DOCKER_PASSWORD
          script: |
            cd ~/frontend/
            make password=$DOCKER_PASSWORD login
            make pull webssja/ssja_prod
            make run-local-prod
            make logout
