# name: deploy-website

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     env:
#       IMAGE_TAG: ${{ github.sha }} 
#     steps:
#       - uses: actions/checkout@v2
#       - run: make build-remote
#       - run: make password=$DOCKER_PASSWORD login
#         env:
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#       - run: make push-remote
#       - run: make logout
#       - uses: appleboy/ssh-action@master
#         env:
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_PRIVATE_KEY }}
#           envs: DOCKER_PASSWORD
#           script: |
#             cd ~/frontend/
#             make password=$DOCKER_PASSWORD login
#             make pull webssja/ssja_prod
#             make run-local-prod
#             make logout

name: deploy-website

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2

      # This was the line causing the error. It's now corrected.
      # FROM: make build-remote
      # TO:   make build-local
      - name: Build Docker Image
        run: make build-local

      - name: Log in to Docker Hub
        run: make password=$DOCKER_PASSWORD login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to Docker Hub
        run: make push-remote

      - name: Log out from Docker Hub
        run: make logout

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          envs: DOCKER_PASSWORD
          script: |
            cd ~/frontend/
            make password=$DOCKER_PASSWORD login
            # Using the new, clearer command from the Makefile
            make pull-remote
            make run-prod
            make logout
