name: Deploy Website

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # مرحله ساخت ایمیج اصلاح شده است
      - name: Build Docker Image
        # ما مقدار Secret را مستقیماً به عنوان پارامتر به دستور 'make' پاس می‌دهیم
        run: make build-local API_KEY=${{ secrets.NEXT_PUBLIC_MAPIR_KEY }}

      - name: Log in to Docker Hub
        run: make login
        env:
          # نام کاربری داکر شما باید به عنوان یک Secret تعریف شود
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to Docker Hub
        run: make push-remote

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd ~/frontend/
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            make pull-remote
            make run-prod
            docker logout

