# name: deploy-website

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     env:
#       IMAGE_TAG: ${{ github.sha }} 
#     steps:
#       - uses: actions/checkout@v2
#       - run: make build-remote
#       - run: make password=$DOCKER_PASSWORD login
#         env:
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#       - run: make push-remote
#       - run: make logout
#       - uses: appleboy/ssh-action@master
#         env:
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_PRIVATE_KEY }}
#           envs: DOCKER_PASSWORD
#           script: |
#             cd ~/frontend/
#             make password=$DOCKER_PASSWORD login
#             make pull webssja/ssja_prod
#             make run-local-prod
#             make logout
name: Deploy Website

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: make build-local
        env:
          # تزریق کلید API از Secrets گیت‌هاب به فرآیند بیلد
          API_KEY: ${{ secrets.NEXT_PUBLIC_MAPIR_KEY }}

      - name: Log in to Docker Hub
        run: make login
        env:
          # این متغیرها توسط دستور 'login' در Makefile استفاده می‌شوند
          DOCKER_USERNAME: webssja
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to Docker Hub
        run: make push-remote

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd ~/frontend/
            # لاگین روی سرور برای اینکه بتواند ایمیج را دانلود کند
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "webssja" --password-stdin
            
            # دانلود آخرین نسخه ایمیج
            make pull-remote
            
            # اجرای کانتینر جدید
            make run-prod
            
            # خروج از حساب داکر روی سرور
            docker logout

